export type RealityTag =
  | "食事・生協"
  | "住居・引っ越し"
  | "通学・車"
  | "キャンパス移動"
  | "周辺環境"
  | "気候・地形"
  | "実習・学生生活"
  | "意外な出費";

export type StudentReality = {
  tag: RealityTag;
  trouble: string;
  impact: string;
  solution: string;
  yoshi: string;
  sourceLabel: string;
  sourceUrl: string;
};

export const realityTags: RealityTag[] = [
  "食事・生協",
  "住居・引っ越し",
  "通学・車",
  "キャンパス移動",
  "周辺環境",
  "気候・地形",
  "実習・学生生活",
  "意外な出費",
];

export const studentRealities: Record<string, StudentReality[]> = {
  "東京大学": [
    {
      tag: "キャンパス移動",
      trouble: "前期課程は駒場、医学科の専門課程は主に本郷。通う場所が途中で変わります。",
      impact: "駒場だけを基準に部屋を決めると、本郷中心になった後の通学時間が伸びることがあります。",
      solution: "2年後の本郷通学も想定し、両キャンパスへ出やすい沿線か、更新時の住み替えを選択肢に。",
      yoshi: "合格後も、路線図は見る。",
      sourceLabel: "東京大学 キャンパス案内",
      sourceUrl: "https://www.u-tokyo.ac.jp/ja/about/campus-guide/index.html",
    },
    {
      tag: "住居・引っ越し",
      trouble: "駒場と本郷は都内でも離れており、片方への近さがもう片方への近さとは限りません。",
      impact: "家賃だけで決めると、毎日の乗換回数や定期代が地味に効いてきます。",
      solution: "家賃に加えて「ドアto教室」と定期代を比較。朝の混雑も一度体験してから決めると安心です。",
      yoshi: "家賃の横に、乗換回数も書こう。",
      sourceLabel: "東京大学 キャンパス案内",
      sourceUrl: "https://www.u-tokyo.ac.jp/ja/about/campus-guide/index.html",
    },
    {
      tag: "実習・学生生活",
      trouble: "本郷キャンパスは赤門だけでなく複数の門があり、建物も多め。初見の教室は「本郷に着いた」だけでは着いていません。",
      impact: "門や建物を取り違えると、キャンパス内で最後の10分を使い切ることがあります。",
      solution: "初めて行く建物は前日に入口まで確認。待ち合わせは「キャンパス」ではなく建物名と門まで指定します。",
      yoshi: "赤門で待つ？ いま赤門、閉まってるよ。",
      sourceLabel: "東京大学 本郷地区キャンパスマップ",
      sourceUrl: "https://www.u-tokyo.ac.jp/campusmap/cam01_00_00_j.html",
    },
  ],
  "京都大学": [
    {
      tag: "通学・車",
      trouble: "医学部・病院構内は吉田近衛町。京都駅からは市バス利用が案内されています。",
      impact: "観光シーズンや雨の日は、バス中心の通学だと所要時間が読みづらくなることがあります。",
      solution: "京阪の神宮丸太町駅から徒歩約10分という選択肢も含め、鉄道＋徒歩で組める住居を検討。",
      yoshi: "京都のバス、時間にも雅がある。",
      sourceLabel: "京都大学医学部 アクセス",
      sourceUrl: "https://www.med.kyoto-u.ac.jp/access/",
    },
    {
      tag: "キャンパス移動",
      trouble: "吉田地区は広く、医学部・病院構内と全学共通科目の教室が同じ建物にまとまっているわけではありません。",
      impact: "授業間の移動を甘く見ると、昼食時間が移動時間に変わる日があります。",
      solution: "時間割を組むときは建物位置まで確認。自転車を使う場合も大学の交通ルールを先に確認します。",
      yoshi: "『吉田キャンパス』、意外と一枚岩じゃない。",
      sourceLabel: "京都大学 キャンパスマップ",
      sourceUrl: "https://www.kyoto-u.ac.jp/ja/access/campus/yoshida/map6r-y",
    },
    {
      tag: "気候・地形",
      trouble: "京都の夏は暑く、冬は底冷え。神宮丸太町駅からの徒歩10分も、季節で体感がかなり変わります。",
      impact: "白衣や教科書を抱えた徒歩移動では、汗・雨・冷えへの対策がないと授業前に消耗します。",
      solution: "夏は汗対策と飲み物、冬は脱ぎ着しやすい防寒を。駅からの徒歩時間は真夏・雨天込みで考えます。",
      yoshi: "徒歩10分、京都では四季が上乗せ。",
      sourceLabel: "京都大学医学部 アクセス",
      sourceUrl: "https://www.med.kyoto-u.ac.jp/access/",
    },
  ],
  "大阪大学": [
    {
      tag: "通学・車",
      trouble: "医学科は吹田キャンパス。北千里駅から徒歩約30分、またはモノレール・バス利用です。",
      impact: "最寄駅に着いてからが長く、雨の日や朝一の授業では体感距離が伸びます。",
      solution: "阪大病院前駅・バス停まで含めて通学経路を比較し、徒歩だけの想定にしない。",
      yoshi: "最寄駅＝到着、ではない。",
      sourceLabel: "大阪大学医学部 アクセス",
      sourceUrl: "https://www.med.osaka-u.ac.jp/access/access",
    },
    {
      tag: "キャンパス移動",
      trouble: "大阪大学は豊中・吹田・箕面にキャンパスが分かれ、医学部の専門教育は吹田が中心です。",
      impact: "全学の活動やサークルとの両立では、キャンパス間移動が予定に入ることがあります。",
      solution: "授業だけでなく課外活動の拠点も確認。移動日は予定を詰め込みすぎないのが現実的です。",
      yoshi: "大学が大きいと、移動も大学級。",
      sourceLabel: "大阪大学 キャンパス情報",
      sourceUrl: "https://www.osaka-u.ac.jp/ja/access",
    },
    {
      tag: "食事・生協",
      trouble: "吹田キャンパスは広く、食堂へ行って戻る時間も昼休みに含まれます。",
      impact: "実習場所と食堂が離れている日は、列に並んだところで昼休みが終わりかけることも。",
      solution: "吹田地区の食堂位置と営業時間を確認し、短い日は購買や持参食へ切り替えます。",
      yoshi: "昼休み、食堂までの往復も競技。",
      sourceLabel: "大阪大学生協 食堂・購買",
      sourceUrl: "https://www.osaka-univ.coop/shop/",
    },
  ],
  "東北大学": [
    {
      tag: "キャンパス移動",
      trouble: "医学部は星陵キャンパス。全学教育や課外活動では川内など別地区を使う場面があります。",
      impact: "住む場所を星陵だけで決めると、学年や活動によって移動の負担が変わります。",
      solution: "星陵・川内の双方へ出やすい地下鉄沿線を軸に、実際の時間割が出てから最終調整。",
      yoshi: "仙台、キャンパスも四方に広い。",
      sourceLabel: "東北大学 キャンパスガイド",
      sourceUrl: "https://campus.bureau.tohoku.ac.jp/",
    },
    {
      tag: "気候・地形",
      trouble: "仙台は冬季に路面凍結や積雪への備えが必要な日があります。",
      impact: "自転車だけを前提にすると、冬の朝に通学手段が急に細くなることがあります。",
      solution: "地下鉄・徒歩の代替経路を持ち、滑りにくい靴と防寒具を早めに準備。",
      yoshi: "白衣の前に、冬靴。",
      sourceLabel: "仙台市 冬道の安全情報",
      sourceUrl: "https://www.city.sendai.jp/doro-kanri/kurashi/machi/kotsu/ijikanri/toketsu.html",
    },
    {
      tag: "住居・引っ越し",
      trouble: "春に部屋を決めると、星陵までの道が冬の凍結時にどう見えるかは想像しにくいです。",
      impact: "坂道や日陰の多い経路では、同じ徒歩分数でも冬の負担が増えることがあります。",
      solution: "内見では地下鉄駅・バス停からの代替経路も確認。冬靴を置く玄関スペースも地味に見ます。",
      yoshi: "物件情報に『凍結時徒歩何分』は載ってない。",
      sourceLabel: "仙台市 冬道の安全情報",
      sourceUrl: "https://www.city.sendai.jp/doro-kanri/kurashi/machi/kotsu/ijikanri/toketsu.html",
    },
  ],
  "東京科学大学": [
    {
      tag: "キャンパス移動",
      trouble: "医歯学系の中心は湯島キャンパス。理工学系の大岡山など、大学全体では複数拠点があります。",
      impact: "医工連携の機会がある一方、行事や授業によっては拠点名を見落とすと別の駅へ向かうことに。",
      solution: "予定にはキャンパス名まで登録。「東京科学大学」だけで地図検索しない習慣を。",
      yoshi: "大学名は一つ、駅は一つじゃない。",
      sourceLabel: "Science Tokyo キャンパス紹介",
      sourceUrl: "https://admissions.isct.ac.jp/ja/013/campus",
    },
    {
      tag: "周辺環境",
      trouble: "湯島は都心立地で交通は便利ですが、住居費は場所による差が大きい地域です。",
      impact: "大学徒歩圏だけに絞ると、家賃や部屋の広さの条件が厳しくなることがあります。",
      solution: "丸ノ内線・千代田線・JRなど複数路線を使い、乗換と家賃のバランスで範囲を広げます。",
      yoshi: "近さは正義。家賃も現実。",
      sourceLabel: "Science Tokyo アクセス",
      sourceUrl: "https://www.isct.ac.jp/ja/001/about/campuses-and-offices",
    },
    {
      tag: "食事・生協",
      trouble: "湯島キャンパスは病院と一体の都心型。昼食は学内施設だけでなく周辺店も使えますが、平日昼は混みやすい地域です。",
      impact: "「外に出ればすぐ食べられる」と思っていると、行列で午後の予定が迫ることがあります。",
      solution: "短い昼休み用の店と、時間がある日用の店を分けて開拓。院内店舗の営業時間も確認します。",
      yoshi: "店は多い。空席まで多いとは言ってない。",
      sourceLabel: "東京科学大学 湯島キャンパス",
      sourceUrl: "https://www.isct.ac.jp/ja/001/about/campuses-and-offices/yushima",
    },
  ],
  "名古屋大学": [
    {
      tag: "キャンパス移動",
      trouble: "医学部は鶴舞キャンパス、全学教育は東山キャンパスが中心。学年で生活圏が変わります。",
      impact: "東山だけを基準に住むと、専門課程で鶴舞への通学が増えた際に負担が変わります。",
      solution: "地下鉄・JRで両方へ出やすい場所を選ぶか、専門課程前の住み替えも最初から想定。",
      yoshi: "名大駅だけ見て決めると、後で鶴舞。",
      sourceLabel: "名古屋大学 キャンパスマップ",
      sourceUrl: "https://www.nagoya-u.ac.jp/access-map/index.html",
    },
    {
      tag: "実習・学生生活",
      trouble: "海外臨床実習を目指す場合、大学は1年次からTOEFLなどの準備が必要と案内しています。",
      impact: "高学年になってから考え始めると、英語資格や医学英語の準備期間が足りなくなることがあります。",
      solution: "興味がある段階で交換留学要件を確認し、1年次から英語学習を細く長く続ける。",
      yoshi: "留学の準備、5年生からでは遅い。",
      sourceLabel: "名古屋大学 医学部紹介",
      sourceUrl: "https://nuoc.adm.nagoya-u.ac.jp/2026/igaku/",
    },
    {
      tag: "住居・引っ越し",
      trouble: "1年次の東山と、その後中心になる鶴舞では便利な路線が違います。",
      impact: "1年目だけ完璧な部屋を選ぶと、専門課程から通学の主役が乗換になることがあります。",
      solution: "6年間同じ部屋にこだわらず、更新時期と学年の切替を合わせる案も家賃計画に入れます。",
      yoshi: "部屋の更新、カリキュラムも見て決める。",
      sourceLabel: "名古屋大学 キャンパスマップ",
      sourceUrl: "https://www.nagoya-u.ac.jp/access-map/index.html",
    },
  ],
  "岐阜大学": [
    {
      tag: "通学・車",
      trouble: "柳戸キャンパスへは岐阜駅・名鉄岐阜駅からバス利用が基本です。",
      impact: "朝の道路状況やバス待ちで、駅から大学までの時間がぶれやすい日があります。",
      solution: "始業ぎりぎりの便を避け、雨の日用に一本早い便を決めておく。住居はバス路線も確認。",
      yoshi: "駅に着いても、まだ大学ではない。",
      sourceLabel: "岐阜大学 交通アクセス",
      sourceUrl: "https://www.gifu-u.ac.jp/access/",
    },
    {
      tag: "周辺環境",
      trouble: "大学周辺は駅前型の立地ではなく、買い物やアルバイト先の選択は居住地で差が出ます。",
      impact: "大学への近さだけで部屋を選ぶと、日用品の買い出しや休日の移動が意外に不便な場合があります。",
      solution: "スーパー・ドラッグストア・バス停まで実際に歩き、日常生活の動線で部屋を決める。",
      yoshi: "大学徒歩5分、スーパー徒歩25分問題。",
      sourceLabel: "岐阜大学 キャンパスマップ",
      sourceUrl: "https://www.gifu-u.ac.jp/campus_map/",
    },
    {
      tag: "食事・生協",
      trouble: "柳戸キャンパスでは昼の選択肢が学内施設に集まりやすく、講義終了直後は利用が重なります。",
      impact: "昼休みに「何を食べるか」から考えると、列と移動で休憩時間が短くなりがちです。",
      solution: "生協の店舗・営業時間を先に把握し、混む日は弁当や購買を使い分けます。",
      yoshi: "昼休みの初手、『考える』より『向かう』。",
      sourceLabel: "岐阜大学消費生活協同組合",
      sourceUrl: "https://www.univcoop-tokai.jp/gucoop/",
    },
  ],
  "三重大学": [
    {
      tag: "通学・車",
      trouble: "上浜キャンパスは近鉄江戸橋駅から徒歩約15分。津駅からはバス利用も案内されています。",
      impact: "駅前すぐの大学ではないため、雨風の強い日は最後の徒歩が地味に効きます。",
      solution: "徒歩ルートとバスの両方を把握し、雨具は置き傘ではなく持ち歩けるものを。",
      yoshi: "徒歩15分、晴れの日限定ではない。",
      sourceLabel: "三重大学医学部 交通アクセス",
      sourceUrl: "https://www.med.mie-u.ac.jp/access/access.html",
    },
    {
      tag: "気候・地形",
      trouble: "伊勢湾に近い津市では、雨や風の強い日も想定した通学準備が必要です。",
      impact: "自転車一本に頼ると、天候によって授業前の移動計画が崩れることがあります。",
      solution: "徒歩・バスの代替経路を持ち、レインウェアや防水バッグを準備。",
      yoshi: "傘だけで勝てない日もある。",
      sourceLabel: "津地方気象台 防災情報",
      sourceUrl: "https://www.jma-net.go.jp/tsu/",
    },
    {
      tag: "住居・引っ越し",
      trouble: "江戸橋駅に近い部屋と、買い物に便利な部屋が必ずしも同じではありません。",
      impact: "通学時間を縮めても、食料品や日用品の買い出しが毎回ちょっとした遠征になる場合があります。",
      solution: "大学・駅・スーパーの三角形で物件を比較。自転車利用なら雨の日の買い物手段も確認します。",
      yoshi: "大学徒歩圏。冷蔵庫の補給圏は？",
      sourceLabel: "三重大学 交通アクセス",
      sourceUrl: "https://www.mie-u.ac.jp/map/traffic/",
    },
  ],
  "浜松医科大学": [
    {
      tag: "食事・生協",
      trouble: "大学病院側にはコンビニや平日昼営業のレストラン等がありますが、一般的な総合大学の大規模生協食堂とは使い勝手が異なります。",
      impact: "昼休みの時間帯や休業日に、食事の選択肢が思ったより限られることがあります。",
      solution: "施設の営業時間を確認し、混みそうな日は弁当・軽食を持参。近隣店も入学後早めに開拓します。",
      yoshi: "昼ごはんも、臨床推論が必要。",
      sourceLabel: "浜松医科大学病院 店舗案内",
      sourceUrl: "https://www.hama-med.ac.jp/hos/cent-clin-fac/amenity/index.html",
    },
    {
      tag: "通学・車",
      trouble: "半田山キャンパスへは浜松駅からバス利用で、鉄道駅から徒歩数分という立地ではありません。",
      impact: "遠方からの電車通学では、電車とバスの接続で所要時間が長くなりやすいです。",
      solution: "バス時刻を含む通学時間で住居を比較。自転車・車を使う場合は大学の登録ルールも確認。",
      yoshi: "浜松駅に着いて、後半戦。",
      sourceLabel: "浜松医科大学 交通アクセス",
      sourceUrl: "https://www.hama-med.ac.jp/access.html",
    },
    {
      tag: "気候・地形",
      trouble: "浜松は冬に強い西風が吹く日があり、自転車では距離以上に進みにくく感じることがあります。",
      impact: "往路が追い風でも、帰路で同じ時間とは限りません。荷物が多い日はさらに影響します。",
      solution: "自転車通学でもバス経路を控え、風の強い日は時間に余裕を。荷物は背負える形にします。",
      yoshi: "行きが速い日は、帰りを疑おう。",
      sourceLabel: "浜松市 気候",
      sourceUrl: "https://www.city.hamamatsu.shizuoka.jp/kokusai/intro/climate.html",
    },
  ],
  "千葉大学": [
    {
      tag: "キャンパス移動",
      trouble: "医学部の専門教育は亥鼻キャンパス。大学全体には西千葉など別キャンパスがあります。",
      impact: "全学行事や課外活動の拠点次第で、キャンパス間の移動が生活に入ってきます。",
      solution: "医学部の授業場所だけでなく、参加したい部活・サークルの活動場所も入学前に確認。",
      yoshi: "千葉大、千葉に一か所ではない。",
      sourceLabel: "千葉大学 キャンパス案内",
      sourceUrl: "https://www.chiba-u.jp/campus-life/campus/",
    },
    {
      tag: "通学・車",
      trouble: "亥鼻キャンパスはJR千葉駅からバス利用、または駅から徒歩を組み合わせる立地です。",
      impact: "西千葉キャンパスと同じ感覚で住居を選ぶと、医学部への毎日の移動が長くなることがあります。",
      solution: "亥鼻への通学を主軸にしつつ、西千葉にも出やすいエリアを地図で比較します。",
      yoshi: "『千葉大の近く』は、どの千葉大？",
      sourceLabel: "千葉大学医学部 交通アクセス",
      sourceUrl: "https://inh.m.chiba-u.jp/access/",
    },
    {
      tag: "気候・地形",
      trouble: "亥鼻キャンパスは台地側にあり、千葉駅方面からは平らな駅前だけの感覚では歩けません。",
      impact: "教科書や実習用品が多い日の徒歩は、地図の距離より負担を感じることがあります。",
      solution: "内見時に実際の通学路を荷物ありで歩く。雨天や暑い日はバスへ切り替えられる場所が安心です。",
      yoshi: "『徒歩可』と『毎日快適』は別科目。",
      sourceLabel: "千葉大学医学部 交通アクセス",
      sourceUrl: "https://inh.m.chiba-u.jp/access/",
    },
  ],
  "筑波大学": [
    {
      tag: "通学・車",
      trouble: "キャンパスが南北に長く、大学も自転車・バイクの登録制度を設けています。",
      impact: "徒歩だけでは授業・実習・課外活動の移動が厳しい日があり、自転車が生活インフラになりがちです。",
      solution: "入学後早めに登録し、ライト・雨具・パンク修理先までセットで準備。",
      yoshi: "筑波の自転車、ほぼ第二の学生証。",
      sourceLabel: "筑波大学 自転車・バイク登録",
      sourceUrl: "https://ssc.sec.tsukuba.ac.jp/office-of-student-welfare/bike",
    },
    {
      tag: "意外な出費",
      trouble: "自転車本体に加え、鍵・ライト・雨具・修理などの維持費も発生します。",
      impact: "安さだけで選ぶと故障や盗難対策で買い直しが発生し、結果的に高くつくことがあります。",
      solution: "通学距離に合う車体と丈夫な鍵を選び、年間のメンテナンス費も生活費に入れておく。",
      yoshi: "自転車は買って終わり、ではない。",
      sourceLabel: "筑波大学 交通安全情報",
      sourceUrl: "https://ssc.sec.tsukuba.ac.jp/office-of-student-welfare/bike",
    },
    {
      tag: "周辺環境",
      trouble: "キャンパスが広いため、「大学の近く」という物件でも目的の医学エリアまでの距離はかなり違います。",
      impact: "住所だけで決めると、毎朝キャンパス内を長く縦断する生活になることがあります。",
      solution: "物件検索では大学名より、医学エリアの建物を目的地にして所要時間を測ります。",
      yoshi: "筑波では『大学まで0分、教室まで15分』がある。",
      sourceLabel: "筑波大学 キャンパスマップ",
      sourceUrl: "https://www.tsukuba.ac.jp/campuslife/campus/",
    },
  ],
  "神戸大学": [
    {
      tag: "キャンパス移動",
      trouble: "医学部は楠キャンパス。神戸大学の全学教育・課外活動は六甲台地区など別拠点もあります。",
      impact: "医学部への近さだけで住むと、全学の活動へ参加する日の移動が増えることがあります。",
      solution: "所属予定の部活・サークルの活動場所を確認し、地下鉄やJRで両方向へ動ける場所も比較。",
      yoshi: "神戸大、山にも街にもある。",
      sourceLabel: "神戸大学 キャンパス案内",
      sourceUrl: "https://www.kobe-u.ac.jp/ja/campus-life/general/access/",
    },
    {
      tag: "食事・生協",
      trouble: "楠キャンパスには生協・食堂がありますが、病院と一体の医療系キャンパスで利用時間の確認が重要です。",
      impact: "実習や授業が延びた日に営業時間を逃すと、食事の選択肢が狭くなることがあります。",
      solution: "食堂の営業時間を把握し、遅くなる日は軽食を準備。周辺の店も数軒押さえておきます。",
      yoshi: "食堂のラストオーダーは待ってくれない。",
      sourceLabel: "神戸大学医学部 楠キャンパスマップ",
      sourceUrl: "https://www.med.kobe-u.ac.jp/access/index.html",
    },
    {
      tag: "気候・地形",
      trouble: "楠キャンパス自体は市街地ですが、六甲台地区で活動する日は神戸らしい坂道が加わります。",
      impact: "医学部の通学だけを想定した靴や移動時間では、全学の行事日に予定が詰まりやすくなります。",
      solution: "六甲台へ行く日は駅からのバスも含めて計画。部活の拠点は入部前に必ず確認します。",
      yoshi: "神戸の坂、景色はいい。遅刻には厳しい。",
      sourceLabel: "神戸大学 キャンパス・アクセス",
      sourceUrl: "https://www.kobe-u.ac.jp/ja/campus-life/general/access/",
    },
  ],
  "岡山大学": [
    {
      tag: "キャンパス移動",
      trouble: "医学部は鹿田キャンパス。大学全体の中心である津島キャンパスとは別地区です。",
      impact: "全学活動や部活の場所によっては、鹿田と津島を行き来する予定が生じます。",
      solution: "住居選びでは鹿田への日常通学を優先しつつ、津島への移動手段も確認。",
      yoshi: "岡大の『大学前』、一つとは限らない。",
      sourceLabel: "岡山大学 キャンパスマップ",
      sourceUrl: "https://www.okayama-u.ac.jp/tp/profile/campus_map.html",
    },
    {
      tag: "通学・車",
      trouble: "岡山市内は平坦で自転車を使いやすい一方、雨の日の代替手段も必要です。",
      impact: "自転車前提の距離に住むと、悪天候時にバス時刻や徒歩時間で慌てることがあります。",
      solution: "自転車＋公共交通の二本立てで住居を選び、実習に遅れない代替経路を用意。",
      yoshi: "晴れの国でも、雨具は要る。",
      sourceLabel: "岡山大学医学部 交通アクセス",
      sourceUrl: "https://oumed.okayama-u.ac.jp/access/",
    },
    {
      tag: "キャンパス移動",
      trouble: "鹿田と津島は同じ岡山市内でも、授業間に歩いて気軽に移れる距離ではありません。",
      impact: "部活や手続きの予定を連続で入れると、自転車・バス移動の時間がそのまま空きコマを使います。",
      solution: "移動日は予定をまとめ、どちらのキャンパスかをカレンダーに明記します。",
      yoshi: "岡大の予定、場所まで書いて完成。",
      sourceLabel: "岡山大学 キャンパスマップ",
      sourceUrl: "https://www.okayama-u.ac.jp/tp/profile/campus_map.html",
    },
  ],
  "広島大学": [
    {
      tag: "キャンパス移動",
      trouble: "医学科は霞キャンパス中心ですが、1年次の一部授業は東広島など別キャンパスになる場合があります。",
      impact: "広島市内だけで完結すると思うと、特定日の長距離移動に驚くことがあります。",
      solution: "最新の時間割で履修場所を確認し、東広島へ行く日は交通時間を先に予定へ固定。",
      yoshi: "同じ1限でも、距離が違う。",
      sourceLabel: "広島大学 医学科1年次時間割",
      sourceUrl: "https://mededucation.hiroshima-u.ac.jp/syllabus/",
    },
    {
      tag: "意外な出費",
      trouble: "複数キャンパスへの移動があると、定期券外の交通費が発生することがあります。",
      impact: "回数は多くなくても、往復が重なる時期には学生生活費へじわじわ響きます。",
      solution: "履修場所と大学の連絡手段を確認し、月の交通費に少額の予備枠を設定。",
      yoshi: "キャンパス移動、単位は出ないが交通費は出る。",
      sourceLabel: "広島大学 キャンパス・アクセス",
      sourceUrl: "https://www.hiroshima-u.ac.jp/access",
    },
    {
      tag: "住居・引っ越し",
      trouble: "霞への毎日の近さと、東広島へ行く日の便利さを一つの物件で両立するのは難しめです。",
      impact: "まれな東広島移動のために日常の霞通学を長くすると、6年間では負担が逆転することがあります。",
      solution: "住居は霞への日常通学を優先し、東広島の日は早出・公共交通で対応する前提にします。",
      yoshi: "たまの遠出より、毎日の10分。",
      sourceLabel: "広島大学 キャンパス・アクセス",
      sourceUrl: "https://www.hiroshima-u.ac.jp/access",
    },
  ],
  "信州大学": [
    {
      tag: "気候・地形",
      trouble: "松本は標高が高く、冬は冷え込みや路面凍結への備えが必要です。",
      impact: "自転車・徒歩通学では、朝の移動時間や服装が季節で大きく変わります。",
      solution: "冬用の靴・防寒具を準備し、凍結日は徒歩やバスへ切り替えられる住居を選ぶ。",
      yoshi: "白衣は防寒着ではない。",
      sourceLabel: "松本市 冬の暮らし",
      sourceUrl: "https://www.city.matsumoto.nagano.jp/",
    },
    {
      tag: "実習・学生生活",
      trouble: "参加型臨床実習は長野県内約30病院の協力で行われ、学外の医療機関を経験する機会があります。",
      impact: "実習先によっては早朝移動や普段と異なる交通手段の準備が必要になります。",
      solution: "実習先が決まったら交通・宿泊・持ち物を早めに確認し、移動費も見込んでおく。",
      yoshi: "長野県、実習フィールドも広い。",
      sourceLabel: "信州大学 参加型臨床実習",
      sourceUrl: "https://www.shinshu-u.ac.jp/faculty/medicine/medical_education/150type/",
    },
    {
      tag: "意外な出費",
      trouble: "県内の学外実習では、実習内容だけでなく交通・場合によっては滞在の準備も必要です。",
      impact: "普段の通学定期だけでは収まらない移動費が、実習時期にまとまって出ることがあります。",
      solution: "実習先決定後すぐに大学の案内と補助の有無を確認し、交通費の予備枠を作ります。",
      yoshi: "実習先は学び。交通費は現実。",
      sourceLabel: "信州大学 参加型臨床実習",
      sourceUrl: "https://www.shinshu-u.ac.jp/faculty/medicine/medical_education/150type/",
    },
  ],
};
